with ex as (select 
COD_CARTEIRINHA_BENEFICIARIO,
DAT_ATENDIMENTO_EFETIVO_SINISTRO,
COD_SERVICO,
DSC_SERVICO,
DSC_GRUPO_SERVICO,
DSC_SUBGRUPO_SERVICO,
COD_PRESTADOR,
COD_GRUPO_ECONOMICO_PRESTADOR,
NME_FANTASIA_PRESTADOR,
DSC_CLASSIFICACAO_SINISTRO,
NME_GRUPO_ECONOMICO_PRESTADOR,
DSC_CLASSIFICACAO_SINISTRO_AGRUPADO,
DSC_SCORE_TIPO_CANCER_AGRUPADO,
DSC_ORIGEM_SINISTRO_AGRUPADO,
DSC_ORIGEM_IDENTIFICACAO,
DSC_ORIGEM_IDENTIFICACAO_AGRUPADO,
DSC_FINALIDAD_TRATAMENTO,
SIG_UF_PRESTADOR,
DSC_TIPO_QUIMIOTERAPIA,
DSC_CARTEIRA_ANO,
DSC_ESTADIAMENTO,
DSC_CLASSIFICACAO_MEDICAMENTO,
FLG_VPP_QUIMIOTERAPIA,
FLG_SINISTRO_ONCOLOGICO_VPP,
COD_SERVICO_DETALHADO,
DSC_SERVICO_DETALHADO,
DSC_PADRAO_SERVICO_MEDICAMENTO,
DSC_PRINCIPIO_ATIVO_MEDICAMENTO,
DSC_CLASSIFICACAO_MEDICAMENTO_AGRUPADO,
DSC_TIPO_SINISTRO,
DSC_PADRAO_CLASSIFICACAO_MEDICAMENTO,
DSC_CLASSIFICACAO_VIA_ACESSO,
DSC_ATENDIMENTO_AGRUPADO,
FLG_MEDICAMENTO,
FLG_HONORARIO_MEDICO,
FLG_MATERIAL,
FLG_INTERNACAO,
SGL_UF_RESIDENCIA,
sum(QTD_SERVICO_DETALHADO) as QTD_SERVICO_DETALHADO,
sum(VAL_PAGO_SERVICO_DETALHADO) as VAL_PAGO_SERVICO_DETALHADO
from  tab B 
--where DAT_ATENDIMENTO_EFETIVO_SINISTRO between '2024-01-01' and '2024-12-31'  
group by 
B.COD_CARTEIRINHA_BENEFICIARIO--,A.VPP--,B.NUM_VPP
,DAT_ATENDIMENTO_EFETIVO_SINISTRO
,COD_SERVICO,
DSC_SERVICO,
DSC_GRUPO_SERVICO,
DSC_SUBGRUPO_SERVICO,
DSC_ORIGEM_SINISTRO_AGRUPADO,
DSC_CLASSIFICACAO_MEDICAMENTO,
COD_PRESTADOR,
COD_GRUPO_ECONOMICO_PRESTADOR,
SIG_UF_PRESTADOR,
NME_FANTASIA_PRESTADOR,
DSC_CARTEIRA_ANO,
DSC_CLASSIFICACAO_SINISTRO,
NME_GRUPO_ECONOMICO_PRESTADOR,
DSC_CLASSIFICACAO_SINISTRO_AGRUPADO,
DSC_SCORE_TIPO_CANCER_AGRUPADO,
FLG_MATERIAL,
FLG_INTERNACAO,
SGL_UF_RESIDENCIA,
FLG_MEDICAMENTO,
DSC_ORIGEM_IDENTIFICACAO,
DSC_ORIGEM_IDENTIFICACAO_AGRUPADO,
DSC_FINALIDAD_TRATAMENTO,
DSC_TIPO_QUIMIOTERAPIA,
DSC_ESTADIAMENTO,
FLG_VPP_QUIMIOTERAPIA,
FLG_SINISTRO_ONCOLOGICO_VPP,
COD_SERVICO_DETALHADO,
DSC_SERVICO_DETALHADO,
DSC_PADRAO_SERVICO_MEDICAMENTO,
DSC_PRINCIPIO_ATIVO_MEDICAMENTO,
DSC_CLASSIFICACAO_MEDICAMENTO,
DSC_CLASSIFICACAO_MEDICAMENTO_AGRUPADO,
DSC_TIPO_SINISTRO,
DSC_PADRAO_CLASSIFICACAO_MEDICAMENTO,
DSC_CLASSIFICACAO_VIA_ACESSO,
DSC_ATENDIMENTO_AGRUPADO,
FLG_HONORARIO_MEDICO),
med_ as (select * from ex where upper(DSC_PADRAO_SERVICO_MEDICAMENTO) Like '%ENHERTU%' or upper(DSC_PADRAO_SERVICO_MEDICAMENTO) like '%KEYTRUDA%') ,
med as (select A.* from med_ A left join tab B 
on LPAD(cast(B.COD_CARTEIRINHA_BENEFICIARIO as STRING), 17, '0') = A.COD_CARTEIRINHA_BENEFICIARIO  
--WHERE DAT_ATENDIMENTO_EFETIVO_SINISTRO > SAFE_CAST(Data_da_VPP AS DATE)
 ),--select * from med,
cruz as(select A.*, 
B.COD_CARTEIRINHA_BENEFICIARIO as COD_CARTEIRINHA ,
DAT_ATENDIMENTO_EFETIVO_SINISTRO,
COD_SERVICO,
DSC_SERVICO,
DSC_GRUPO_SERVICO,
DSC_CARTEIRA_ANO,
DSC_SUBGRUPO_SERVICO,
DSC_ORIGEM_SINISTRO_AGRUPADO,
COD_PRESTADOR,
NME_FANTASIA_PRESTADOR,
DSC_CLASSIFICACAO_SINISTRO,
NME_GRUPO_ECONOMICO_PRESTADOR,
DSC_CLASSIFICACAO_SINISTRO_AGRUPADO,
COD_GRUPO_ECONOMICO_PRESTADOR,
DSC_SCORE_TIPO_CANCER_AGRUPADO,
--DSC_CLASSIFICACAO_MEDICAMENTO,
DSC_ORIGEM_IDENTIFICACAO,
DSC_ORIGEM_IDENTIFICACAO_AGRUPADO,
DSC_FINALIDAD_TRATAMENTO,
DSC_TIPO_QUIMIOTERAPIA,
SIG_UF_PRESTADOR,
DSC_ESTADIAMENTO,
FLG_VPP_QUIMIOTERAPIA,
FLG_SINISTRO_ONCOLOGICO_VPP,
COD_SERVICO_DETALHADO,
DSC_SERVICO_DETALHADO,
DSC_PADRAO_SERVICO_MEDICAMENTO,
DSC_PRINCIPIO_ATIVO_MEDICAMENTO,
DSC_CLASSIFICACAO_MEDICAMENTO,
DSC_CLASSIFICACAO_MEDICAMENTO_AGRUPADO,
DSC_TIPO_SINISTRO,
DSC_PADRAO_CLASSIFICACAO_MEDICAMENTO,
DSC_CLASSIFICACAO_VIA_ACESSO,
DSC_ATENDIMENTO_AGRUPADO,
FLG_MEDICAMENTO,
FLG_HONORARIO_MEDICO,
FLG_MATERIAL,
FLG_INTERNACAO,
SGL_UF_RESIDENCIA,
case when cast(IDADE as integer) between 0 and 9 then '0 - 9' 
          when cast(IDADE as integer) between 10 and 19 then '10 - 19' 
          when cast(IDADE as integer) between 20 and 29 then '20 - 29' 
          when cast(IDADE as integer) between 30 and 39 then '30 - 39' 
          when cast(IDADE as integer) between 40 and 49 then '40 - 49' 
          when cast(IDADE as integer) between 50 and 59 then '50 - 59' 
          when cast(IDADE as integer) between 60 and 69 then '60 - 69' 
          when cast(IDADE as integer) between 70 and 79 then '70 - 79' 
          when cast(IDADE as integer) > 80 then '80+' 
end as PERFIL_ETARIO ,
CASE
          when CID = 'C50%' then 'C50' 
          when CID = 'C16%' then 'C16' 
      	  when CID = 'C34%' then 'C34'
      	  when CID = 'C54%' then 'C54'
      	  ELSE CID
end as CID_AGRUPADO ,
upper(PARECER_ANALISE_GEIES) as Parecer_Geies,
 CASE
    WHEN UPPER(IHQ) LIKE '%HER2+++/3%' OR UPPER(IHQ) LIKE '%HER2 3+%' THEN 'TRIPLO POSITIVO'
    WHEN UPPER(IHQ) LIKE '%HER2 1+%' OR UPPER(IHQ) LIKE '%HER 2%' OR UPPER(IHQ) LIKE '%HER2+%' OR UPPER(IHQ) LIKE '%HER2 1/3%'
    OR UPPER(IHQ) LIKE '%HER2+' OR UPPER(IHQ) LIKE '%HER2 +%' OR UPPER(IHQ) LIKE '%RE+  RP+   Her2 1/3%'
    OR UPPER(IHQ) LIKE '%HER2+%' OR UPPER(IHQ) LIKE '%HER2+%' OR UPPER(IHQ) LIKE '%HER2+  EGFR NEG  ALK NEG  PD L1 NEG%'THEN 'HER2 POSITIVO'
    WHEN UPPER(IHQ) LIKE '%HER2 2+%' THEN 'DUPLO POSITIVO'
    WHEN UPPER(IHQ) LIKE '%HER2 0 TRIPLO NEGATIVO%' OR UPPER(IHQ) LIKE '%HER2 0%' OR UPPER(IHQ) LIKE '%TRIPLO NEGATIVO%' THEN 'TRIPLO NEGATIVO'
    ELSE IHQ
END AS classificacao_IHQ,
FORMAT_DATE('%Y%m', DATE_TRUNC(DAT_ATENDIMENTO_EFETIVO_SINISTRO, MONTH)) as ano_mes,
sum(QTD_SERVICO_DETALHADO) as QTD_SERVICO_DETALHADO,
sum(VAL_PAGO_SERVICO_DETALHADO) as VAL_PAGO_SERVICO_DETALHADO
from  tab A
left join med B 
on LPAD(cast(A.COD_CARTEIRINHA_BENEFICIARIO as STRING), 17, '0') = B.COD_CARTEIRINHA_BENEFICIARIO
group by all),
--estados as (select COD_CARTEIRINHA_BENEFICIARIO,SGL_UF_RESIDENCIA from tab ),
resultado AS (SELECT A.*--,B.SGL_UF_RESIDENCIA,
FROM cruz A
--LEFT JOIN estados B
--on LPAD(cast(A.COD_CARTEIRINHA_BENEFICIARIO as STRING), 17, '0') = B.COD_CARTEIRINHA_BENEFICIARIO 
),
onco_final_ as (SELECT 
COD_CARTEIRINHA_BENEFICIARIO,NME_BENEFICIARIO,Idade,Sexo,VPP,
DAT_ATENDIMENTO_EFETIVO_SINISTRO,Data_da_VPP,
Prestador,
CID,
Descricao_do_CID,
IHQ,
VPP_IHQ,
Estadiamento,
ECOG,
Finalidade_do_tratamento,
Tipo_de_Quimioterapia,
Plano_terapeutico,
Parecer_VPP,
Relatorio_Medico_X_Parecer_VPP,
Relatorio_Medico_X_Dados_estruturados,
--Campo_Incorreto_OU_em_Branco,
Liminar,
LM_Associado_ao_Medicamento,
Parecer_analise_GEIES,
TIPO_MARCA,
--Coluna_1,
COD_CARTEIRINHA,
COD_SERVICO,
DSC_SERVICO,
DSC_GRUPO_SERVICO,
DSC_CARTEIRA_ANO,
DSC_SUBGRUPO_SERVICO,
COD_PRESTADOR,
NME_FANTASIA_PRESTADOR,
DSC_CLASSIFICACAO_SINISTRO,
COD_GRUPO_ECONOMICO_PRESTADOR,
NME_GRUPO_ECONOMICO_PRESTADOR,
DSC_CLASSIFICACAO_SINISTRO_AGRUPADO,
DSC_SCORE_TIPO_CANCER_AGRUPADO,
DSC_CLASSIFICACAO_MEDICAMENTO,
DSC_ORIGEM_IDENTIFICACAO,
DSC_ORIGEM_IDENTIFICACAO_AGRUPADO,
DSC_FINALIDAD_TRATAMENTO,
DSC_TIPO_QUIMIOTERAPIA,
DSC_ESTADIAMENTO,
FLG_VPP_QUIMIOTERAPIA,
FLG_SINISTRO_ONCOLOGICO_VPP,
COD_SERVICO_DETALHADO,
DSC_SERVICO_DETALHADO,
DSC_PADRAO_SERVICO_MEDICAMENTO,
DSC_PRINCIPIO_ATIVO_MEDICAMENTO,
DSC_CLASSIFICACAO_MEDICAMENTO_AGRUPADO,
DSC_TIPO_SINISTRO,
DSC_ORIGEM_SINISTRO_AGRUPADO,
DSC_PADRAO_CLASSIFICACAO_MEDICAMENTO
DSC_CLASSIFICACAO_VIA_ACESSO,
DSC_ATENDIMENTO_AGRUPADO,
FLG_MEDICAMENTO,
FLG_HONORARIO_MEDICO,
SIG_UF_PRESTADOR,
FLG_MATERIAL,
FLG_INTERNACAO,
SGL_UF_RESIDENCIA,
PERFIL_ETARIO,
CID_AGRUPADO,
Parecer_Geies,
classificacao_IHQ,
ano_mes,
QTD_SERVICO_DETALHADO,
VAL_PAGO_SERVICO_DETALHADO
FROM resultado

group by all ),
onco_final as(select A.*,B.DSC_MOTIVO_EXCLUSAO_BENEFICIARIO, 
case when DAT_FIM_VIGENCIA_PLANO = '9999-12-31' then 'ATIVO'
else 'INATIVO'
end as status_beneficiario
from onco_final_ A left join tab2 B on LPAD(cast(A.COD_CARTEIRINHA_BENEFICIARIO as string), 17, '0') = B.COD_CARTEIRINHA_BENEFICIARIO
group by ALL),
TempoUso AS (
    SELECT
        COD_CARTEIRINHA_BENEFICIARIO,
        DSC_PADRAO_SERVICO_MEDICAMENTO,
        DAT_ATENDIMENTO_EFETIVO_SINISTRO,
        LAG(DAT_ATENDIMENTO_EFETIVO_SINISTRO) OVER (PARTITION BY COD_CARTEIRINHA_BENEFICIARIO, DSC_PADRAO_SERVICO_MEDICAMENTO ORDER BY DAT_ATENDIMENTO_EFETIVO_SINISTRO) AS DataAnterior,
        DATE_DIFF(DAT_ATENDIMENTO_EFETIVO_SINISTRO, LAG(DAT_ATENDIMENTO_EFETIVO_SINISTRO) OVER (PARTITION BY COD_CARTEIRINHA_BENEFICIARIO, DSC_PADRAO_SERVICO_MEDICAMENTO ORDER BY DAT_ATENDIMENTO_EFETIVO_SINISTRO), DAY) AS TempoUsoDias,
        MIN(DAT_ATENDIMENTO_EFETIVO_SINISTRO) OVER (PARTITION BY COD_CARTEIRINHA_BENEFICIARIO, DSC_PADRAO_SERVICO_MEDICAMENTO) AS DataInicio,
        MAX(DAT_ATENDIMENTO_EFETIVO_SINISTRO) OVER (PARTITION BY COD_CARTEIRINHA_BENEFICIARIO, DSC_PADRAO_SERVICO_MEDICAMENTO) AS DataFim,
        DATE_DIFF(MAX(DAT_ATENDIMENTO_EFETIVO_SINISTRO) OVER (PARTITION BY COD_CARTEIRINHA_BENEFICIARIO, DSC_PADRAO_SERVICO_MEDICAMENTO), MIN(DAT_ATENDIMENTO_EFETIVO_SINISTRO) OVER (PARTITION BY COD_CARTEIRINHA_BENEFICIARIO, DSC_PADRAO_SERVICO_MEDICAMENTO), DAY) AS DiferencaTotalDias
    FROM med_
),
resultado_tempo AS (SELECT
    COD_CARTEIRINHA_BENEFICIARIO,
    DSC_PADRAO_SERVICO_MEDICAMENTO,
    DataInicio,
    DataFim,
    CASE
    WHEN DiferencaTotalDias <= 30 THEN '1 Mês'
    WHEN DiferencaTotalDias <= 365 THEN 
        CAST(FLOOR(DiferencaTotalDias/30) AS STRING) || ' Meses'
    WHEN DiferencaTotalDias <= 365*2 THEN 
        '1 Ano e ' || CAST(FLOOR((DiferencaTotalDias - 365)/30) AS STRING) || ' Meses'
    WHEN DiferencaTotalDias <= 365*3 THEN 
        '2 Anos e ' || CAST(FLOOR((DiferencaTotalDias - 365*2)/30) AS STRING) || ' Meses'
    WHEN DiferencaTotalDias <= 365*4 THEN 
        '3 Anos e ' || CAST(FLOOR((DiferencaTotalDias - 365*3)/30) AS STRING) || ' Meses'
    WHEN DiferencaTotalDias <= 365*5 THEN 
        '4 Anos e ' || CAST(FLOOR((DiferencaTotalDias - 365*4)/30) AS STRING) || ' Meses'
    ELSE 'Mais de 5 Anos' 
END AS DiferencaTotalDias ,
    ROUND(AVG(TempoUsoDias), 2) AS TempoMedioUso,
    MIN(CASE WHEN TempoUsoDias > 0 THEN TempoUsoDias ELSE NULL END) AS MenorTempoUso,
    MAX(TempoUsoDias) AS MaiorTempoUso
FROM
    TempoUso
WHERE TempoUsoDias IS NOT NULL 
GROUP BY
    COD_CARTEIRINHA_BENEFICIARIO,
    DSC_PADRAO_SERVICO_MEDICAMENTO,
    DataInicio,
    DataFim,
    DiferencaTotalDias
ORDER BY
    COD_CARTEIRINHA_BENEFICIARIO,
    DSC_PADRAO_SERVICO_MEDICAMENTO),
tabela_final as(SELECT A.*,
 	B.DataInicio,
    B.DataFim,
    B.DiferencaTotalDias,
    B.TempoMedioUso,
    B.MenorTempoUso,
    B.MaiorTempoUso
FROM onco_final A
LEFT JOIN resultado_tempo B
ON LPAD(cast(A.COD_CARTEIRINHA_BENEFICIARIO as string), 17, '0') = B.COD_CARTEIRINHA_BENEFICIARIO)
select * from tabela_final
group by all 
